/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as StudioSettingsRouteImport } from './routes/studio/settings'
import { Route as StudioPropertiesRouteImport } from './routes/studio/properties'
import { Route as StudioPagesRouteImport } from './routes/studio/pages'
import { Route as StudioMediaRouteImport } from './routes/studio/media'
import { Route as StudioLoginRouteImport } from './routes/studio/login'
import { Route as StudioInquiriesRouteImport } from './routes/studio/inquiries'
import { Route as StudioContactRouteImport } from './routes/studio/contact'
import { Route as StudioBlogsRouteImport } from './routes/studio/blogs'
import { Route as StudioAccountRouteImport } from './routes/studio/account'
import { Route as PropertiesSlugRouteImport } from './routes/properties/$slug'
import { Route as PagesSlugRouteImport } from './routes/pages/$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs/$slug'
import { Route as StudioPagesSlugRouteImport } from './routes/studio/pages/$slug'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPropertiesRoute = StudioPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPagesRoute = StudioPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMediaRoute = StudioMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLoginRoute = StudioLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StudioRoute,
} as any)
const StudioInquiriesRoute = StudioInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => StudioRoute,
} as any)
const StudioContactRoute = StudioContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBlogsRoute = StudioBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAccountRoute = StudioAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StudioRoute,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPagesSlugRoute = StudioPagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StudioPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/studio': typeof StudioRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/studio/account': typeof StudioAccountRoute
  '/studio/blogs': typeof StudioBlogsRoute
  '/studio/contact': typeof StudioContactRoute
  '/studio/inquiries': typeof StudioInquiriesRoute
  '/studio/login': typeof StudioLoginRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/pages': typeof StudioPagesRouteWithChildren
  '/studio/properties': typeof StudioPropertiesRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/blogs/': typeof BlogsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/pages/$slug': typeof StudioPagesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/studio/account': typeof StudioAccountRoute
  '/studio/blogs': typeof StudioBlogsRoute
  '/studio/contact': typeof StudioContactRoute
  '/studio/inquiries': typeof StudioInquiriesRoute
  '/studio/login': typeof StudioLoginRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/pages': typeof StudioPagesRouteWithChildren
  '/studio/properties': typeof StudioPropertiesRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/blogs': typeof BlogsIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/studio': typeof StudioIndexRoute
  '/studio/pages/$slug': typeof StudioPagesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/studio': typeof StudioRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/studio/account': typeof StudioAccountRoute
  '/studio/blogs': typeof StudioBlogsRoute
  '/studio/contact': typeof StudioContactRoute
  '/studio/inquiries': typeof StudioInquiriesRoute
  '/studio/login': typeof StudioLoginRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/pages': typeof StudioPagesRouteWithChildren
  '/studio/properties': typeof StudioPropertiesRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/blogs/': typeof BlogsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/pages/$slug': typeof StudioPagesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/studio'
    | '/blogs/$slug'
    | '/pages/$slug'
    | '/properties/$slug'
    | '/studio/account'
    | '/studio/blogs'
    | '/studio/contact'
    | '/studio/inquiries'
    | '/studio/login'
    | '/studio/media'
    | '/studio/pages'
    | '/studio/properties'
    | '/studio/settings'
    | '/blogs/'
    | '/properties/'
    | '/studio/'
    | '/studio/pages/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/blogs/$slug'
    | '/pages/$slug'
    | '/properties/$slug'
    | '/studio/account'
    | '/studio/blogs'
    | '/studio/contact'
    | '/studio/inquiries'
    | '/studio/login'
    | '/studio/media'
    | '/studio/pages'
    | '/studio/properties'
    | '/studio/settings'
    | '/blogs'
    | '/properties'
    | '/studio'
    | '/studio/pages/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/studio'
    | '/blogs/$slug'
    | '/pages/$slug'
    | '/properties/$slug'
    | '/studio/account'
    | '/studio/blogs'
    | '/studio/contact'
    | '/studio/inquiries'
    | '/studio/login'
    | '/studio/media'
    | '/studio/pages'
    | '/studio/properties'
    | '/studio/settings'
    | '/blogs/'
    | '/properties/'
    | '/studio/'
    | '/studio/pages/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  StudioRoute: typeof StudioRouteWithChildren
  BlogsSlugRoute: typeof BlogsSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PropertiesSlugRoute: typeof PropertiesSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/properties': {
      id: '/studio/properties'
      path: '/properties'
      fullPath: '/studio/properties'
      preLoaderRoute: typeof StudioPropertiesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/pages': {
      id: '/studio/pages'
      path: '/pages'
      fullPath: '/studio/pages'
      preLoaderRoute: typeof StudioPagesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/media': {
      id: '/studio/media'
      path: '/media'
      fullPath: '/studio/media'
      preLoaderRoute: typeof StudioMediaRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/login': {
      id: '/studio/login'
      path: '/login'
      fullPath: '/studio/login'
      preLoaderRoute: typeof StudioLoginRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/inquiries': {
      id: '/studio/inquiries'
      path: '/inquiries'
      fullPath: '/studio/inquiries'
      preLoaderRoute: typeof StudioInquiriesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/contact': {
      id: '/studio/contact'
      path: '/contact'
      fullPath: '/studio/contact'
      preLoaderRoute: typeof StudioContactRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/blogs': {
      id: '/studio/blogs'
      path: '/blogs'
      fullPath: '/studio/blogs'
      preLoaderRoute: typeof StudioBlogsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/account': {
      id: '/studio/account'
      path: '/account'
      fullPath: '/studio/account'
      preLoaderRoute: typeof StudioAccountRouteImport
      parentRoute: typeof StudioRoute
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/pages/$slug': {
      id: '/studio/pages/$slug'
      path: '/$slug'
      fullPath: '/studio/pages/$slug'
      preLoaderRoute: typeof StudioPagesSlugRouteImport
      parentRoute: typeof StudioPagesRoute
    }
  }
}

interface StudioPagesRouteChildren {
  StudioPagesSlugRoute: typeof StudioPagesSlugRoute
}

const StudioPagesRouteChildren: StudioPagesRouteChildren = {
  StudioPagesSlugRoute: StudioPagesSlugRoute,
}

const StudioPagesRouteWithChildren = StudioPagesRoute._addFileChildren(
  StudioPagesRouteChildren,
)

interface StudioRouteChildren {
  StudioAccountRoute: typeof StudioAccountRoute
  StudioBlogsRoute: typeof StudioBlogsRoute
  StudioContactRoute: typeof StudioContactRoute
  StudioInquiriesRoute: typeof StudioInquiriesRoute
  StudioLoginRoute: typeof StudioLoginRoute
  StudioMediaRoute: typeof StudioMediaRoute
  StudioPagesRoute: typeof StudioPagesRouteWithChildren
  StudioPropertiesRoute: typeof StudioPropertiesRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAccountRoute: StudioAccountRoute,
  StudioBlogsRoute: StudioBlogsRoute,
  StudioContactRoute: StudioContactRoute,
  StudioInquiriesRoute: StudioInquiriesRoute,
  StudioLoginRoute: StudioLoginRoute,
  StudioMediaRoute: StudioMediaRoute,
  StudioPagesRoute: StudioPagesRouteWithChildren,
  StudioPropertiesRoute: StudioPropertiesRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  StudioRoute: StudioRouteWithChildren,
  BlogsSlugRoute: BlogsSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  PropertiesSlugRoute: PropertiesSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
